export const CHANGE_ACTIVE_LINK = "CHANGE_ACTIVE_LINK";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_MONEY_REQUEST = "GET_MONEY_REQUEST";
export const GET_MONEY_SUCCESS = "GET_MONEY_SUCCESS";
export const GET_MONEY_FAILURE = "GET_MONEY_FAILURE";

export const GET_TRANSACTIONS_REQUEST = "GET_TRANSACTIONS_REQUEST";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_FAILURE = "GET_TRANSACTIONS_FAILURE";

export const LOG_OUT = "LOG_OUT";
export const CHANGE_MESSAGE = "CHANGE_MESSAGE";
